# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
validate-pages:
  stage: test
  before_script:
    - mkdir ~/validator
    - apk add git python2 curl
  script:
    - >
      for file in $(ls *.htm*); do
          curl -H "Content-Type: text/html; charset=utf-8" --data-binary @$file https://validator.nu/?out=json
       done

